name: ADO ArchiveFiles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Action Zip
      uses: papeloto/action-zip@v1
      with:
        files: archive
        dest: archive.zip
    - name: Echo message
      run: echo archive.zip
    - name: 7z install and compress files
      run:  |-
        sudo apt-get install p7zip-full
        7z u -mx=9 archive.7z archive
      continue-on-error: true
    - name: Tar files
      run: tar -cf archive.tar archive --overwrite
      continue-on-error: true
    - name: Install and zip files
      run:  |-
        sudo apt-get install zip
        zip -r -u archive.zip archive
      continue-on-error: true
      
   
