name: ADO ArchiveFiles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install 7z
      run:  sudo apt-get install p7zip-full
    - name: 7z files
      run:  7z a -mx=9 archive.7z archive
    - name: Run echo
      run: echo "we are here"
    - name: Tar files
      run: tar -cf archive.tar archive --overwrite
    - name: Install zip
      run: sudo apt-get install zip
    - name: Zip files
      run:  zip -r -u archive.zip archive
      
   
