name: Dir Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: MKDIR & CD
      run: |
        pwd # /home/runner/work/try/try
        mkdir hello
        cd hello
        pwd # /home/runner/work/try/try/hello
    - name: WORKING DIRECTORY
      working-directory: $project_dir
      run: |
        pwd
        echo $project_dir
      env: 
        project_dir: "./dbz"
    - name: WORKING DIRECTORY 2
      working-directory: $project
      run: |
        pwd
        echo $project
      env: 
        project: ./dbz
        
