name: ADO Gradle + SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download and unzip Sonarqube
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.3.zip
          apt-get -y install unzip
          sudo unzip sonarqube-7.3.zip -d /opt
          sudo mv /opt/sonarqube-7.3 /opt/sonarqube
          sudo chown -R administrator:administrator /opt/sonarqube/

      - name: Build with Gradle
        run: ./gradlew build sonarqube -Dsonar.projectKey=rogerprz_Workflows -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        
