

name: MS Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Dependency - setup-msbuild
      uses: microsoft/setup-msbuild@v1
      with: 
        vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer'
    
    - name: MSBuild
      working-directory: src
      continue-on-error: true
      run: msbuild MyProject.csproj

    - name: Run MsTest
      working-directory: src
      continue-on-error: true
      run: mstest 'MSTest Visual Studio 2015' /resultsfile:TestResult.txt
#     - name: find-mstest
#       run: '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /help'
#     - name: Run msbuild
#       shell: cmd
#       run: msbuild MSTestWorkflow/MsTestWorkflow.csproj -restore -p:OutputDir=C:\MySolutionOutput;ContinueOnError=true

