name: Tar Results

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
    steps:
    - name: Create Artifacts files
      run: |-
        echo build/libs/**/*.jar >> include.txt
        echo old/path/ >> excludes.txt
        echo !**/*~ >> excludes.txt
        echo !**/#*# >> excludes.txt
        echo !**/.#* >> excludes.txt
        echo !**/%*% >> excludes.txt
        echo !**/._* >> excludes.txt
        echo !**/CVS >> excludes.txt
        echo !**/CVS/** >> excludes.txt
        echo !**/.cvsignore >> excludes.txt
        echo !**/SCCS >> excludes.txt
        echo !**/SCCS/** >> excludes.txt
        echo !**/vssver.scc >> excludes.txt
        echo !**/.svn >> excludes.txt
        echo !**/.svn/** >> excludes.txt
        echo !**/.DS_Store >> excludes.txt
        echo !**/.git >> excludes.txt
        echo !**/.git/** >> excludes.txt
        echo !**/.gitattributes >> excludes.txt
        echo !**/.gitignore >> excludes.txt
        echo !**/.gitmodules >> excludes.txt
        echo !**/.hg >> excludes.txt
        echo !**/.hg/** >> excludes.txt
        echo !**/.hgignore >> excludes.txt
        echo !**/.hgsub >> excludes.txt
        echo !**/.hgsubstate >> excludes.txt
        echo !**/.hgtags >> excludes.txt
        echo !**/.bzr >> excludes.txt
        echo !**/.bzr/** >> excludes.txt
        echo !**/.bzrignore >> excludes.txt
    - name: Create Tar
      run: tar -c --exclude-from=excludes.txt --files-from=include.txt -f artifacts.tar
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Archive Tar
        path: artifacts.tar
