name: Tar Results

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
    steps:
    - name: Create Artifact files
      run: |-
        echo archive/path >> include
        echo old/path/ >> exclude
        echo "START"
        cat include
        echo "MID"
        cat exclude
        echo "END"
    - name: Create Tar
      run: "tar -c --exclude-from=exclude --files-from=include -f artifacts.tar"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Archive Tar
        path: artifacts.tar
