name: Tar Upload Artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Create Artifact files
      run: |
       echo some_text >> include.txt
        #echo "archive/path" >> "include.txt"
        # echo "temple/path/two" >> "include.txt"
        # echo "tower/path" >> "${{ github.workspace }}/include.txt"
        
       # echo > "exclude.txt
        #echo "base/path" >> "include.txt"
       # echo "archive/path" >> "exclude.txt"
        
    - name: Tar files
      run: "tar -c --exclude-from='exclude.txt' --files-from='include.txt' my-artifact.tar"
    
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: My Artifact
        path: "my-artifact.tar"    
