name: Tar Results

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create Artifact files
      run: |
        echo 'archive/path' >> include.txt
        echo 'old/path/' >> exclude.txt
        echo !**/*~ >> exclude.txt
        echo !**/#*# >> exclude.txt
        echo !**/.#* >> exclude.txt
        echo !**/%*% >> exclude.txt
        echo !**/._* >> exclude.txt
        echo !**/CVS >> exclude.txt
        echo !**/CVS/** >> exclude.txt
    - name: Create Tar
      run: "tar -c --exclude-from=exclude.txt --files-from=include.txt -f artifacts.tar"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Archive Tar
        path: artifacts.tar
