name: Powershell Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to

    steps:
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@2
      with:
        name: freestyle-raven
        path: |-
          freestyle-raven
          path/to/artifact, path/**/*
          !artifact-not-to-copy-field
        if-no-files-found: error
        retention-days: 0
